# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
